name = "inkstone-demo"
compatibility_date = "2026-05-01"
workers_dev = false
preview_urls = false

[assets]
directory = "./dist/demo"
not_found_handling = "single-page-application"

[observability]
enabled = true
